name: countries-app

services:

  # See: https://hub.docker.com/_/mysql
  # ASKED CHAT GPT: I have a /docker-compose.yml file and a /src/db/schema.sql How do I create my sql db with the schema file?
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: countriesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: countriesdb
      FLASK_ENV: development
    networks:
      - frontend
      - backend
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./src/api:/app  # Mounts ./src/api from host to /app in the container
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    environment:
      - API_ADDRESS=api
      - API_PORT=5000
    ports:
      - "${WEB_PORT}:8501"
      

    # # todo cant get this to work
    # depends_on:
    #   api:
    #     condition: service_healthy
    networks:
      - frontend
      - backend
    volumes:
      - ./src/web:/app  # Mounts ./src/web from host to /app in the container

volumes:
  db_data:

networks:
  frontend:
  backend:

